export const AUTH = "AUTH";

export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const FETCH_QUESTIONS_FAILED = "FETCH_QUESTIONS_FAILED";

export const SET_LOADING = "SET_LOADING";

export const FETCH_ANSWERS = "FETCH_ANSWERS";
export const FETCH_ANSWERS_SUCCESS = "FETCH_ANSWERS_SUCCESS";
export const FETCH_ANSWERS_FAILED = "FETCH_ANSWERS_FAILED";

export const ADD_ANSWER = "ADD_ANSWER";
export const ADD_ANSWER_SUCCESS = "ADD_ANSWER_SUCCESS";
export const ADD_ANSWER_FAILED = "ADD_ANSWER_FAILED";

export const SET_OPTIONS = "SET_OPTIONS";
